### ISSUE TITLE
Error deploying to github pages

### ISSUE THREAD

**Issue by chrisdel101** [piazzai/hacked-jekyll#7]
I'm trying to deploy to GH pages and I get this error 
` Logging at level: debug Configuration file: /github/workspace/./_config.yml Theme: hacked-jekyll github-pages 231 | Error: The hacked-jekyll theme could not be found. `

This is my config.yml. I don't know how to use baseurl or url, so they might be causing the error.   They are commented out for now. I'm just using the default URL that GH pages assigns me. Gem works locally, and is in Gemfile

```
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: '' # the subpath of your site, e.g. /blog
#url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: hacked-jekyll
plugins:
  - jekyll-feed
```

**Comment by chrisdel101** [comment]
So I missed this line in the config
`gem "github-pages", group: :jekyll_plugins`. This process is terribly documented (by Jekyll).  Adding it gives me this error:
`bundle install` (bundle update alone gives same error)
```
Could not find compatible versions

    Because github-pages >= 117, < 178 depends on jekyll-sass-converter = 1.5.0
      and github-pages >= 44, < 147 depends on liquid = 3.0.6,
github-pages >= 44, < 178 requires jekyll-sass-converter = 1.5.0 or liquid
= 3.0.6.
(1) So, because github-pages >= 28, < 44 depends on jekyll = 2.4.0,
github-pages >= 28, < 178 requires jekyll-sass-converter = 1.5.0 or liquid
= 3.0.6 or jekyll = 2.4.0.

    Because github-pages >= 9, < 14 depends on kramdown = 1.2.0
      and github-pages < 9 depends on kramdown = 1.0.2,
      github-pages < 14 requires kramdown = 1.0.2 OR = 1.2.0.
    And because github-pages >= 14, < 32 depends on kramdown = 1.3.1,
      github-pages < 32 requires kramdown = 1.0.2 OR = 1.2.0 OR = 1.3.1.
And because github-pages >= 28, < 178 requires jekyll-sass-converter = 1.5.0
or liquid = 3.0.6 or jekyll = 2.4.0 (1),
github-pages < 178 requires jekyll-sass-converter = 1.5.0 or liquid =
3.0.6 or jekyll = 2.4.0 or kramdown = 1.0.2 OR = 1.2.0 OR = 1.3.1.
    And because github-pages >= 178 depends on jekyll-sass-converter = 1.5.2
      and jekyll >= 4.3.0 depends on jekyll-sass-converter >= 2.0, < 4.0,
jekyll >= 4.3.0 requires liquid = 3.0.6 or kramdown = 1.0.2 OR = 1.2.0 OR
= 1.3.1.
    And because jekyll >= 4.3.0 depends on kramdown >= 2.3.1, < 3.A
      and jekyll >= 3.5.0 depends on liquid ~> 4.0,
      jekyll >= 4.3.0 cannot be used.
    So, because every version of hacked-jekyll depends on jekyll >= 4.3.2, < 5.A
      and Gemfile depends on hacked-jekyll >= 0,
      version solving has failed.
```

**Comment by ghost** [comment]
github is not recognizing this theme

debug Configuration file: /github/workspace/./_config.yml Theme: hacked-jekyll github-pages 231 | Error: The hacked-jekyll theme could not be found. 

https://github.com/vkaxcore/VKAX/actions/runs/8511471876

**Comment by chrisdel101** [comment]
@realsetvin so this theme cannot be used with GH pages? Or it's a config error with my/our setup?

**Comment by piazzai** [comment]
The theme _can_ be used with GitHub Pages. However, it can't be used with the `github-pages` gem, which is a convenience gem that loads a bunch of dependencies to enable features you can use on GitHub Pages.

This is ultimately because the `hacked-jekyll` gem requires a more recent version of Jekyll (4.3.2 or above), while `github-pages` strictly requires another version (3.9.5). You can verify these dependencies here:

https://rubygems.org/gems/hacked-jekyll
https://rubygems.org/gems/github-pages

**Solution 1:** Use the `hacked-jekyll` gem. Do not use the `github-pages` gem. Instead, figure out what components you need for your GitHub Pages website (such as `jekyll-feed`) and load these individually.

**Solution 2:** Use the `github-pages` gem. Do not use the `hacked-jekyll` gem. To install the theme without using the gem, copy all files in this repo to your website's directory, except the following:

* `demo/`
* `docs/`
* `Gemfile`
* `LICENSE`
* `README.md`
* `hacked-jekyll.gemspec`
* `screenshot.png`

Then, copy the files `demo/_data/json.yml`, `demo/index.md`, and `demo/404.md` and place them in your website's directory. After doing this, create a new `Gemfile`:

```ruby
source "https://rubygems.org"
gem "github-pages"
```

Run `bundle install`. This will result in a working website.

**Comment by chrisdel101** [comment]
This my first time using Jekyll and I'm finding it's much more time consuming than I had hoped for. I also suck at it. I'll give this one last go before I give up since I built my site around this theme, and I like it. 

I'm trying your solution 2. So obv I still need it to run locally. What about the config.yml? The `theme` param is erroring since `hacked-jekyll` was there. It's not running if I remove all the gems as U said.

My dir structure looks like this. index.md is your index also layouts.
![Screenshot 2024-04-02 at 12 56 02 PM](https://github.com/piazzai/hacked-jekyll/assets/14151974/34e271b5-de5e-4d80-80ea-e96ae21ca74b)

gem file (not sure if U meant to delete all other gems, but I did):
```
source "https://rubygems.org"
gem "github-pages"
```

config.yml:

```

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://mysite.github.io' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: hacked-jekyll
plugins:
  - jekyll-feed
```

Thanks for any help

**Comment by piazzai** [comment]
The `_config.yml` is wrong. As I mentioned, you need to copy the one included in the repo's main folder. Here it is:
https://raw.githubusercontent.com/piazzai/hacked-jekyll/master/_config.yml

This is the site structure you should aim for. All files are copied from `hacked-jekyll/` (the repo's main folder) unless otherwise specified.

```bash
.
├── 404.md # this is copied from hacked-jekyll/demo/
├── assets
│   ├── android-chrome-192x192.png
│   ├── android-chrome-512x512.png
│   ├── apple-touch-icon.png
│   ├── css
│   │   ├── normalize.css
│   │   ├── open-color.css
│   │   └── styles.css
│   ├── favicon-16x16.png
│   ├── favicon-32x32.png
│   ├── favicon.ico
│   ├── js
│   │   └── typed.umd.js
│   ├── site.webmanifest
│   └── webfonts
│       ├── hack-italic-subset.woff2
│       └── hack-regular-subset.woff2
├── _config.yml
├── _data
│   └── json.yml # this is copied from hacked-jekyll/demo/
├── Gemfile # this is created from scratch
├── Gemfile.lock
├── index.md # this is copied from hacked-jekyll/demo/
└── _layouts
    ├── 404.html
    ├── default.html
    └── home.html
```

You seem to have everything, with some differences and extras that should not prevent the site from working. So I expect it to work if you use the config file above. Let me know if that is not the case.

**Comment by chrisdel101** [comment]
Ahh yes. This does work, but it only renders the index page. None of the other pages work since the file paths overrite the root `/myapp` -> `/work` instead of `/myapp/work`. 
I guess this is a GH pages issue I'll have to google to fix. 
if you happen to know a quick fix let me know. 
Thanks for your help!

**Comment by piazzai** [comment]
That is not a GitHub Pages issue. It's a problem with the theme (also mentioned in #5) that I should have fixed earlier.

It is fixed now, in the latest release of the theme (v2.1.1). Please make sure to update your local files. Then, you should properly configure your website in `_config.yml` by setting:

```yaml
baseurl: "/myapp"
url: "https://www.yoursite.com"
```

Just like the `demo/_config.yml` file in the latest release:

https://github.com/piazzai/hacked-jekyll/blob/b3adbe723cfbedded2b23ebed9b3448fc816a386/demo/_config.yml#L3-L4

**Comment by chrisdel101** [comment]
So I had it working I thought?? WTF. Not sure what happened. 
So now I am getting `bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/3.3.0/bin/jekyll)` locally. 
gemfile:
```
source "https://rubygems.org"
gem "github-pages"
```
config: 
```
source "https://rubygems.org"
gem "github-pages"

config:
title: ""
description: ""
baseurl: ""
url: ""

lowercase: true
color_bg: var(--oc-gray-9)
color_punct: var(--oc-green-9)
color_keyval: var(--oc-green-4)
color_hover: var(--oc-green-5)
show_quotes: true
show_commas: true
target: "_self"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


```

So I'm back to the local version again. How can this run without Jekkly? https://github.com/chrisdel101/chris_del_portfolio
EDIT: I added webrick and it seems to have fixed it locally. Not sure about GH pages.

**Comment by piazzai** [comment]
It should. I downloaded your repo, added `gem "webrick"` to the Gemfile, reran `bundle install`, and at that point `bundle exec jekyll serve` and `bundle exec jekyll build` generated the site without errors.

Loading webrick is not required if you use the `hacked-jekyll` gem because it is loaded automatically as a dependency. But because you are now not using that gem in order to use `github-pages`, you have to load `webrick` explicitly.

The purpose of the `github-pages` gem is precisely to emulate the GitHub Pages environment locally, so if with that gem everything works, it should work once the site is deployed to GitHub Pages as well.

But you still have to update your local theme files, and set `url` and `baseurl` in the config file, as explained in my last comment. This is necessary to correctly host your site at an address like www.yoursite.com/myapp.

**Comment by chrisdel101** [comment]
It still won't work for me. Locally adding anything into `baseurl` makes all the pages 404. 
I added it back in and pushed the changes, and still only the index page runs.
`https://chrisdel101.github.io/chris-del-portfolio/`. Click any link to see.

QUICK FIX: I hardcoded the links in the json file for now. So it's working, but doesn't work for both local and GH-pages

**Comment by piazzai** [comment]
I forked your site and made a few changes. Everything works on my end. I just made a pull request to your repo.

https://github.com/chrisdel101/chris-del-portfolio/pull/1

**Comment by chrisdel101** [comment]
I appreciate you doing all this to help me. But I ran the PR locally and the index page still will not even run. It's a 404 unless I delete the `baseurl`. So even the basic problem persists.
I think at this point I'm going to abandon this project. I don't want to invest the time into learning Jekyll, which would be required for me to understand how to fix these problems. 
Thanks again
